name: Test PID Control

on: [push, pull_request]

jobs:
  test_pid:
    name: Test PID Control
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 2.7
        uses : actions/setup-python@v2
        with :
          python-version: 2.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

          sudo apt-get update -y
          sudo apt-get install -y python-rospy
          export PYTHONPATH="${PYTHONPATH}:/usr/lib/python2.7/dist-packages"
          source ~/.bashrc

          pip freeze
          dpkg -L python-rospy
      
      - name: Run Tests
        run : |
          pytest ./sauvc_control/tests/


  style_check:
    name: Pylint Style Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 2.7
        uses : actions/setup-python@v2
        with :
          python-version: 2.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Pylint Style Check
        run : |
          pylint --exit-zero -j 0 ./sauvc_control/src/sauvc_control ./sauvc_control/tests/test_pid_controller.py
          
